---
AllCops:
  DisplayCopNames: true
  Exclude:
    - "bin/*"
    - "Gemfile"
    - "tmp/**/*"
    - "vendor/**/*"

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: no_comma

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Style/DoubleNegation:
  Enabled: false
